import { CartProductItem } from '../../services/cart-service';

export type CollectionCategory =
  | 'all'
  | 'brand'
  | 'romance'
  | 'bold'
  | 'sweet'
  | 'night'
  | 'office'
  | 'men'
  | 'women';

export type CollectionProduct = CartProductItem & {
  categories: Exclude<CollectionCategory, 'all'>[];
};

export const COLLECTION_PRODUCTS: CollectionProduct[] = [
  {
    id: 'perfume-ni-sherwin',
    perfName: 'Perfume ni Sherwin',
    description: 'Signature warm eau de parfum',
    imagePath: 'assets/images/carosuelsahome/HermesA.png',
    size: '50mL',
    price: 79,
    originalPrice: 99,
    discountRate: 0.2,
    categories: ['brand', 'bold', 'men'],
  },
  {
    id: 'midnight-romance',
    perfName: 'Midnight Romance',
    description: 'Deep floral scent for evenings',
    imagePath: 'assets/images/carosuelsahome/Peoplenight1.png',
    size: '50mL',
    price: 89,
    originalPrice: 119,
    discountRate: 0.25,
    categories: ['romance', 'night', 'women'],
  },
  {
    id: 'sweet-bloom',
    perfName: 'Sweet Bloom',
    description: 'Fresh floral perfume',
    imagePath: 'assets/images/carosuelsahome/Flower1.png',
    size: '30mL',
    price: 69,
    originalPrice: 89,
    discountRate: 0.22,
    categories: ['sweet', 'romance', 'women'],
  },
  {
    id: 'office-mist',
    perfName: 'Office Mist',
    description: 'Clean everyday office scent',
    imagePath: 'assets/images/carosuelsahome/Reed1.png',
    size: '50mL',
    price: 99,
    originalPrice: 129,
    discountRate: 0.23,
    categories: ['office', 'brand', 'men'],
  },
  {
    id: 'velvet-date',
    perfName: 'Velvet Date',
    description: 'Warm scent for date nights',
    imagePath: 'assets/images/carosuelsahome/Flower2.png',
    size: '50mL',
    price: 89,
    originalPrice: 119,
    discountRate: 0.25,
    categories: ['romance', 'night', 'sweet'],
  },
  {
    id: 'blush-moment',
    perfName: 'Blush Moment',
    description: 'Soft sweet floral perfume',
    imagePath: 'assets/images/carosuelsahome/Flower3.png',
    size: '30mL',
    price: 69,
    originalPrice: 89,
    discountRate: 0.22,
    categories: ['romance', 'sweet', 'women'],
  },
  {
    id: 'amber-command',
    perfName: 'Amber Command',
    description: 'Bold amber with strong projection',
    imagePath: 'assets/images/carosuelsahome/vstease1.png',
    size: '50mL',
    price: 109,
    originalPrice: 139,
    discountRate: 0.22,
    categories: ['bold', 'night', 'men'],
  },
  {
    id: 'noir-oud',
    perfName: 'Noir Oud',
    description: 'Dark woody evening perfume',
    imagePath: 'assets/images/carosuelsahome/vstease2.png',
    size: '50mL',
    price: 119,
    originalPrice: 149,
    discountRate: 0.2,
    categories: ['bold', 'night', 'men'],
  },
  {
    id: 'vanilla-cloud',
    perfName: 'Vanilla Cloud',
    description: 'Cozy vanilla and soft musk',
    imagePath: 'assets/images/carosuelsahome/img5.png',
    size: '50mL',
    price: 75,
    originalPrice: 95,
    discountRate: 0.21,
    categories: ['sweet', 'women', 'brand'],
  },
  {
    id: 'sugar-petal',
    perfName: 'Sugar Petal',
    description: 'Playful sweet floral scent',
    imagePath: 'assets/images/carosuelsahome/img4.png',
    size: '30mL',
    price: 65,
    originalPrice: 85,
    discountRate: 0.24,
    categories: ['sweet', 'romance', 'women'],
  },
  {
    id: 'boardroom-citrus',
    perfName: 'Boardroom Citrus',
    description: 'Polished citrus for work days',
    imagePath: 'assets/images/carosuelsahome/Reed2.png',
    size: '50mL',
    price: 95,
    originalPrice: 125,
    discountRate: 0.24,
    categories: ['office', 'men', 'brand'],
  },
  {
    id: 'clean-agenda',
    perfName: 'Clean Agenda',
    description: 'Light musk for daily wear',
    imagePath: 'assets/images/carosuelsahome/Reed3.png',
    size: '50mL',
    price: 85,
    originalPrice: 105,
    discountRate: 0.19,
    categories: ['office', 'women', 'brand'],
  },
  {
    id: 'after-dark-spice',
    perfName: 'After Dark Spice',
    description: 'Spiced scent for night parties',
    imagePath: 'assets/images/carosuelsahome/vstease3.png',
    size: '50mL',
    price: 105,
    originalPrice: 135,
    discountRate: 0.22,
    categories: ['night', 'bold', 'men'],
  },
  {
    id: 'moonlit-rose',
    perfName: 'Moonlit Rose',
    description: 'Romantic rose for evening plans',
    imagePath: 'assets/images/carosuelsahome/People3.png',
    size: '50mL',
    price: 92,
    originalPrice: 118,
    discountRate: 0.22,
    categories: ['night', 'romance', 'women'],
  },
  {
    id: 'cedar-luxe',
    perfName: 'Cedar Luxe',
    description: 'Clean cedar and smooth spice',
    imagePath: 'assets/images/carosuelsahome/Verte1.png',
    size: '50mL',
    price: 98,
    originalPrice: 128,
    discountRate: 0.23,
    categories: ['men', 'bold', 'office'],
  },
  {
    id: 'rose-silk',
    perfName: 'Rose Silk',
    description: 'Elegant floral daily perfume',
    imagePath: 'assets/images/carosuelsahome/verte3.png',
    size: '50mL',
    price: 88,
    originalPrice: 112,
    discountRate: 0.21,
    categories: ['women', 'romance', 'brand'],
  },
];
